### ISSUE TITLE
The generate_voice function returns just none

### ISSUE THREAD

**Issue by Kajitsy** [Xtr4F/PyCharacterAI#2]
I had to dig a little bit into the code and output a response, in the end I get it, even if I use an example

![image](https://github.com/Xtr4F/PyCharacterAI/assets/94784342/66f3ae8b-aa82-4f5e-a7d7-3c3016b8d1c9)

**Comment by kashishjhamtani** [comment]
from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/Users/mac-37/Documents/PyCharacterAI/PyCharacterAI/types/__init__.py)

Could you please help me with the above error?
Actually I think the types folder is conflicting with the inbuilt types module.So when I change the folder name to custom_types it throws me the below error.

    from PyCharacterAI.custom_types.message import Message, MessageHistory, OutgoingMessage, Reply
ModuleNotFoundError: No module named 'PyCharacterAI.custom_types'

**Comment by Kajitsy** [comment]
> I need help that how you run this project? Is there any command for it because it couldn't found anything similar in Readme file?

I downloaded the repository and just added print(response), sorry if I misunderstood you

**Comment by Xtr4F** [comment]
Hi. At the time this issue was created, the library was very outdated. A lot of things have changed in the api over the last year, so I've released a new version 2.0 that fixes many bugs and includes many new features, but unfortunately breaks backwards compatibility. If you are still interested in this project, you can check out the new version and read the documentation.
